// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdLpEa8aRaIol6rtDNscmlvajHVc0Cv-g',
    appId: '1:627529000508:web:53719d7a977d6b6d820539',
    messagingSenderId: '627529000508',
    projectId: 'push-e50b3',
    authDomain: 'push-e50b3.firebaseapp.com',
    storageBucket: 'push-e50b3.appspot.com',
    measurementId: 'G-W3N2KJL1PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzEAANaihO_OQhzhYQhdYuVekGvSxWM1E',
    appId: '1:627529000508:android:78f0b2cbf531b74a820539',
    messagingSenderId: '627529000508',
    projectId: 'push-e50b3',
    storageBucket: 'push-e50b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwJj2tGMJvbn3SiVrKFznyPlHEXLe15Y8',
    appId: '1:627529000508:ios:7c4effb43410cc1c820539',
    messagingSenderId: '627529000508',
    projectId: 'push-e50b3',
    storageBucket: 'push-e50b3.appspot.com',
    iosBundleId: 'com.example.push',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwJj2tGMJvbn3SiVrKFznyPlHEXLe15Y8',
    appId: '1:627529000508:ios:2dadf4ed32cee342820539',
    messagingSenderId: '627529000508',
    projectId: 'push-e50b3',
    storageBucket: 'push-e50b3.appspot.com',
    iosBundleId: 'com.example.push.RunnerTests',
  );
}
